crypto_tickers = {
    'BTC-USD': 'Bitcoin',
    'ETH-USD': 'Ethereum',
    'USDT-USD': 'Tether',
    'BNB-USD': 'Binance Coin',
    'USDC-USD': 'USD Coin',
    'XRP-USD': 'XRP',
    'ADA-USD': 'Cardano',
    'DOGE-USD': 'Dogecoin',
    'SOL-USD': 'Solana',
    'TRX-USD': 'TRON',
    'DOT-USD': 'Polkadot',
    'MATIC-USD': 'Polygon',
    'LTC-USD': 'Litecoin',
    'AVAX-USD': 'Avalanche',
    'SHIB-USD': 'Shiba Inu',
    'WBTC-USD': 'Wrapped Bitcoin',
    'LEO-USD': 'UNUS SED LEO',
    'LINK-USD': 'Chainlink',
    'ATOM-USD': 'Cosmos',
    'ETC-USD': 'Ethereum Classic',
    'XMR-USD': 'Monero',
    'FIL-USD': 'Filecoin',
    'STETH-USD': 'Lido Staked Ether',
    'BCH-USD': 'Bitcoin Cash',
    'TON-USD': 'Toncoin',
    'QNT-USD': 'Quant',
    'LDO-USD': 'Lido DAO',
    'APT-USD': 'Aptos',
    'NEAR-USD': 'NEAR Protocol',
    'ARB-USD': 'Arbitrum',
    'CRO-USD': 'Cronos',
    'VET-USD': 'VeChain',
    'ALGO-USD': 'Algorand',
    'HNT-USD': 'Helium',
    'ICP-USD': 'Internet Computer',
    'MKR-USD': 'Maker',
    'XLM-USD': 'Stellar',
    'AAVE-USD': 'Aave',
    # 'GRT-USD': 'The Graph',
    'FRAX-USD': 'Frax',
    'FTM-USD': 'Fantom',
    'RPL-USD': 'Rocket Pool',
    # 'BTT-USD': 'BitTorrent',
    'HT-USD': 'Huobi Token',
    'LUNC-USD': 'Terra Classic',
    'TUSD-USD': 'TrueUSD',
    'SAND-USD': 'The Sandbox',
    'EGLD-USD': 'MultiversX',
    'AXS-USD': 'Axie Infinity'
}
